from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, content: str) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def shape_import() -> str:
    source = read("src/gfx/archetypes/carnageFoot.ts")
    imports = re.findall(r"import[\s\S]*?from\s+['\"][^'\"]+['\"]", source)
    result = next((item for item in imports if "rect" in item and "circle" in item), None)
    if result is None:
        raise RuntimeError("Could not locate the pixel-shape helper import")
    for name in ("Shape", "rect", "circle", "ellipse", "line"):
        if name not in result:
            result = re.sub(r"import\s*\{", f"import {{ {name},", result, count=1)
    return result


VARIANTS = [
    "corrupted-infantry", "corrupted-longbow", "corrupted-pike", "corrupted-knight",
    "corrupted-monk", "corrupted-surgeon", "husk", "flenser", "butcher",
    "flensing-host", "ripjaw", "ripjaw-alpha", "skinrider", "carrion-choir",
    "shrike", "headsman", "monstrum", "great-maw", "carrion-widow",
    "widow-queen", "charnel-engine", "flesh-wall", "incarnation",
]


def visual_module() -> str:
    union = "\n".join(f"  | '{name}'" for name in VARIANTS)
    return f"""{shape_import()}

/**
 * Design-specific silhouette overlays for the Carnage roster.
 *
 * Earlier builds mapped complete evolutionary lines onto one shared body.
 * These variants keep the existing deterministic rig and animation, then add
 * the anatomy and equipment that identifies the exact stage. Every shape is
 * therefore generated by the game itself and remains compatible with icons,
 * poses, enemy tinting and the procedural texture cache.
 */
export type CarnageVisualVariant =
{union}

const R = rect as unknown as (...args: any[]) => Shape
const C = circle as unknown as (...args: any[]) => Shape
const E = ellipse as unknown as (...args: any[]) => Shape
const L = line as unknown as (...args: any[]) => Shape

type ShapeBucket = {{ key: string; value: Shape[]; score: number }}

function shade(color: number, factor: number): number {{
  const channel = (shift: number): number =>
    Math.max(0, Math.min(255, Math.round(((color >> shift) & 255) * factor)))
  return (channel(16) << 16) | (channel(8) << 8) | channel(0)
}}

function buckets(root: unknown): ShapeBucket[] {{
  const found: ShapeBucket[] = []
  const seen = new Set<unknown>()
  const visit = (value: unknown, key: string, depth: number): void => {{
    if (!value || typeof value !== 'object' || depth > 4 || seen.has(value)) return
    seen.add(value)
    if (Array.isArray(value)) {{
      if (value.length === 0 || value.every(item => item && typeof item === 'object')) {{
        const low = key.toLowerCase()
        let score = 0
        if (/body|torso|chest|core/.test(low)) score += 100
        if (/head|skull|face/.test(low)) score += 85
        if (/back|rear|wing|mount/.test(low)) score += 75
        if (/weapon|hand|arm|front/.test(low)) score += 65
        found.push({{ key: low, value: value as Shape[], score }})
      }}
      return
    }}
    for (const [childKey, child] of Object.entries(value as Record<string, unknown>)) {{
      visit(child, childKey, depth + 1)
    }}
  }}
  visit(root, '', 0)
  return found.sort((a, b) => b.score - a.score)
}}

function pick(all: ShapeBucket[], pattern: RegExp, fallback: number): Shape[] | null {{
  return all.find(entry => pattern.test(entry.key))?.value ?? all[fallback]?.value ?? null
}}

function add(target: Shape[] | null, ...items: Shape[]): void {{
  if (target) target.push(...items)
}}

/** Adds a readable stage-specific profile to the existing animated archetype. */
export function applyCarnageVisualVariant<T>(visual: any, art: T): T {{
  const variant = visual?.variant as CarnageVisualVariant | undefined
  if (!variant || !art || typeof art !== 'object') return art

  const all = buckets(art)
  if (all.length === 0) return art
  const body = pick(all, /body|torso|chest|core/, 0)
  const head = pick(all, /head|skull|face/, 1)
  const back = pick(all, /back|rear|wing|mount/, 2)
  const weapon = pick(all, /weapon|hand|arm|front/, 3)

  const flesh = visual.flesh ?? 0xa64b47
  const cloth = visual.cloth ?? 0x4d2927
  const metal = visual.metal ?? 0x6a6260
  const blood = 0x941f29
  const dark = 0x441018
  const bone = 0xd8c9a8
  const blue = 0x4d9fe0
  const shadow = shade(flesh, 0.45)
  const pale = shade(flesh, 1.25)

  switch (variant) {{
    case 'corrupted-infantry':
      add(body, R(24, 25, 4, 18, blood), R(30, 28, 2, 14, bone), R(35, 29, 2, 12, bone))
      add(head, C(39, 16, 3, dark), L(35, 14, 42, 10, 2, bone))
      break
    case 'corrupted-longbow':
      add(back, E(15, 20, 9, 23, dark), C(18, 22, 2, blue), C(19, 28, 2, blue))
      add(weapon, L(47, 11, 55, 31, 2, bone), L(55, 31, 47, 51, 2, bone), L(47, 11, 47, 51, 1, blood))
      break
    case 'corrupted-pike':
      add(back, L(22, 18, 15, 28, 3, flesh), L(22, 30, 14, 39, 3, flesh))
      add(weapon, L(40, 40, 62, 8, 3, bone), L(58, 12, 63, 5, 3, blood), C(48, 27, 2, dark))
      break
    case 'corrupted-knight':
      add(body, E(19, 20, 34, 30, metal), R(20, 30, 7, 19, blood), C(48, 32, 7, flesh))
      add(head, L(30, 14, 34, 4, 4, bone), L(41, 15, 46, 6, 4, metal))
      break
    case 'corrupted-monk':
      add(back, C(33, 18, 13, dark), C(33, 18, 9, shade(cloth, 0.7)), C(33, 18, 4, blood))
      add(weapon, L(48, 16, 49, 52, 3, bone), C(48, 13, 5, blood), C(48, 13, 2, pale))
      break
    case 'corrupted-surgeon':
      add(head, E(28, 14, 15, 8, pale), R(31, 18, 10, 2, dark))
      add(back, L(20, 20, 11, 38, 2, blood), L(20, 23, 12, 49, 2, metal), C(12, 49, 3, blood))
      add(weapon, L(45, 31, 58, 44, 2, metal), L(56, 42, 62, 39, 3, bone))
      break
    case 'husk':
      add(body, R(24, 27, 3, 16, bone), R(30, 27, 3, 17, bone), R(36, 29, 3, 14, bone), E(19, 39, 10, 6, dark))
      add(head, E(34, 13, 12, 10, pale), C(40, 17, 2, dark), L(30, 19, 22, 31, 4, flesh))
      break
    case 'flenser':
      add(back, L(24, 22, 10, 14, 4, blood), L(24, 37, 8, 49, 4, flesh))
      add(weapon, L(42, 27, 61, 13, 3, bone), L(42, 38, 61, 52, 3, blood), C(59, 15, 3, dark), C(59, 50, 3, dark))
      break
    case 'butcher':
      add(body, E(17, 19, 38, 34, flesh), R(18, 34, 35, 8, blood), C(48, 31, 6, dark))
      add(weapon, R(45, 21, 8, 28, metal), R(50, 14, 12, 21, bone), L(19, 23, 8, 48, 4, blood))
      break
    case 'flensing-host':
      add(back, L(25, 26, 7, 10, 5, flesh), L(25, 31, 4, 27, 5, flesh), L(26, 37, 8, 53, 5, flesh))
      add(weapon, L(42, 21, 61, 8, 3, bone), L(44, 28, 63, 24, 3, blood), L(43, 37, 62, 46, 3, bone), L(40, 44, 56, 61, 3, blood))
      break
    case 'ripjaw':
      add(body, E(16, 30, 37, 16, shadow), E(42, 31, 19, 12, flesh))
      add(head, E(45, 28, 18, 13, flesh), E(51, 35, 13, 8, dark), C(51, 31, 2, pale))
      break
    case 'ripjaw-alpha':
      add(body, E(13, 27, 43, 20, flesh), L(20, 30, 24, 12, 5, blood), L(31, 29, 37, 10, 5, bone))
      add(head, E(43, 24, 21, 17, shadow), E(51, 35, 14, 9, dark), C(51, 28, 2, pale))
      break
    case 'skinrider':
      add(back, E(20, 18, 27, 18, cloth), R(30, 7, 8, 19, flesh), C(34, 8, 5, pale), L(30, 20, 18, 37, 3, blood))
      add(body, E(10, 34, 48, 17, shadow), L(19, 37, 8, 48, 4, flesh))
      add(head, E(43, 30, 21, 14, flesh), E(53, 37, 11, 7, dark))
      break
    case 'carrion-choir':
      add(back, C(23, 17, 7, pale), C(34, 13, 7, flesh), C(45, 18, 7, pale), C(34, 21, 18, dark))
      add(body, E(18, 24, 33, 28, cloth), L(23, 30, 13, 51, 3, bone), L(45, 30, 55, 51, 3, bone))
      break
    case 'shrike':
      add(back, L(28, 27, 7, 7, 7, dark), L(28, 27, 12, 37, 5, blood), L(38, 27, 58, 8, 7, blood), L(38, 27, 54, 38, 5, dark))
      add(body, R(29, 17, 8, 34, shadow), L(31, 47, 35, 62, 4, bone))
      add(head, L(31, 15, 35, 3, 4, bone))
      break
    case 'headsman':
      add(body, E(15, 18, 42, 36, metal), R(15, 34, 43, 9, dark))
      add(head, E(24, 7, 22, 17, metal), R(29, 17, 12, 2, blood))
      add(weapon, L(43, 25, 58, 54, 5, bone), R(49, 12, 14, 22, metal))
      break
    case 'monstrum':
      add(body, E(10, 14, 49, 43, flesh), C(22, 27, 8, blood), C(45, 35, 10, shadow), R(24, 43, 23, 7, dark))
      add(head, C(40, 16, 8, pale), L(33, 14, 37, 3, 4, bone))
      break
    case 'great-maw':
      add(body, E(7, 16, 54, 42, shadow), E(18, 21, 44, 31, flesh))
      add(head, E(34, 20, 30, 28, dark), L(40, 25, 43, 35, 3, bone), L(48, 24, 51, 35, 3, bone), L(56, 25, 58, 35, 3, bone), L(40, 45, 44, 36, 3, bone), L(50, 46, 53, 36, 3, bone))
      break
    case 'carrion-widow':
      add(back, L(29, 28, 5, 7, 8, blood), L(29, 29, 12, 38, 5, dark), L(38, 28, 61, 6, 8, dark), L(38, 29, 55, 39, 5, blood))
      add(body, E(25, 27, 18, 22, flesh), C(34, 23, 5, pale))
      break
    case 'widow-queen':
      add(back, L(27, 31, 2, 7, 9, dark), L(27, 32, 10, 43, 6, blood), L(41, 31, 63, 6, 9, blood), L(41, 32, 56, 45, 6, dark), C(34, 38, 17, shadow), C(34, 38, 10, blood))
      add(head, L(25, 16, 28, 3, 3, bone), L(34, 14, 39, 2, 3, bone), L(42, 17, 47, 5, 3, bone), C(35, 18, 7, pale))
      add(body, L(22, 42, 6, 60, 3, bone), L(28, 46, 18, 63, 3, bone), L(42, 46, 52, 63, 3, bone), L(47, 42, 63, 60, 3, bone))
      break
    case 'charnel-engine':
      add(body, R(9, 29, 50, 22, metal), E(17, 19, 35, 25, flesh), C(20, 50, 8, dark), C(50, 50, 8, dark))
      add(back, L(20, 29, 20, 6, 4, bone), C(20, 7, 6, blood), L(35, 27, 35, 3, 4, metal), C(35, 7, 7, pale), L(50, 29, 56, 8, 4, bone))
      break
    case 'flesh-wall':
      add(body, R(5, 13, 55, 41, shadow), E(4, 19, 24, 32, flesh), E(38, 17, 23, 34, flesh), R(13, 20, 4, 30, bone), R(27, 16, 4, 36, bone), R(42, 19, 4, 32, bone), C(18, 29, 4, blood), C(46, 36, 5, dark))
      break
    case 'incarnation':
      add(back, L(27, 30, 1, 1, 10, dark), L(27, 31, 7, 43, 7, blood), L(41, 30, 63, 1, 10, blood), L(41, 31, 57, 45, 7, dark), L(23, 23, 11, 3, 5, bone), L(44, 23, 56, 2, 5, bone))
      add(body, E(14, 13, 39, 45, shadow), C(34, 33, 11, blood), L(20, 35, 3, 55, 5, flesh), L(48, 35, 64, 55, 5, flesh))
      add(head, L(26, 18, 29, 2, 4, bone), L(39, 18, 44, 1, 4, bone), C(35, 18, 8, pale), C(32, 17, 2, blue), C(38, 17, 2, blood))
      add(weapon, L(47, 29, 63, 12, 5, metal), L(59, 15, 64, 5, 4, bone), L(20, 31, 3, 17, 5, blood))
      break
  }}
  return art
}}
"""


def update_types() -> None:
    path = "src/data/types.ts"
    source = read(path)
    if "CarnageVisualVariant" not in source:
        source = "import type { CarnageVisualVariant } from '../gfx/carnageVisualVariants'\n" + source
    if "variant?: CarnageVisualVariant" not in source:
        patterns = [r"(export\s+interface\s+UnitVisual\s*\{)", r"(export\s+type\s+UnitVisual\s*=\s*\{)"]
        for pattern in patterns:
            if re.search(pattern, source):
                source = re.sub(
                    pattern,
                    r"\1\n  /** Design-specific procedural silhouette for Carnage progression. */\n  variant?: CarnageVisualVariant",
                    source,
                    count=1,
                )
                break
        else:
            raise RuntimeError("UnitVisual declaration not found")
    write(path, source)


def update_dispatcher() -> None:
    path = "src/gfx/unitArt.ts"
    source = read(path)
    if "applyCarnageVisualVariant" not in source:
        lines = source.splitlines()
        last_import = max(index for index, line in enumerate(lines) if line.startswith("import "))
        lines.insert(last_import + 1, "import { applyCarnageVisualVariant } from './carnageVisualVariants'")
        source = "\n".join(lines) + "\n"

    if "applyCarnageVisualVariant(visual" not in source:
        starts = list(re.finditer(r"export\s+(?:default\s+)?function\s+\w+\s*\(([^)]*)\)[^{]*\{", source))
        chosen: tuple[int, int] | None = None
        for match in starts:
            if "visual" not in match.group(1):
                continue
            depth = 0
            end = None
            for index in range(match.end() - 1, len(source)):
                if source[index] == "{":
                    depth += 1
                elif source[index] == "}":
                    depth -= 1
                    if depth == 0:
                        end = index + 1
                        break
            if end is not None and ".kind" in source[match.start():end]:
                chosen = (match.start(), end)
                break
        if chosen is None:
            raise RuntimeError("Unit art dispatcher not found")
        start, end = chosen
        block = source[start:end]
        block = re.sub(
            r"\breturn\s+([^;\n]+);",
            lambda match: f"return applyCarnageVisualVariant(visual, {match.group(1)});",
            block,
        )
        source = source[:start] + block + source[end:]
    write(path, source)


UNIT_VARIANTS = {
    "nk_husk": "husk",
    "nk_flenser": "flenser",
    "nk_butcher": "butcher",
    "nk_flensing_host": "flensing-host",
    "nk_ripjaw": "ripjaw",
    "nk_ripjaw_alpha": "ripjaw-alpha",
    "nk_skinrider": "skinrider",
    "nk_carrion_choir": "carrion-choir",
    "nk_shrike": "shrike",
    "nk_headsman": "headsman",
    "nk_monstrum": "monstrum",
    "nk_great_maw": "great-maw",
    "nk_carrion_widow": "carrion-widow",
    "nk_widow_queen": "widow-queen",
    "nk_charnel_engine": "charnel-engine",
    "nk_flesh_wall": "flesh-wall",
    "nk_incarnation": "incarnation",
}


def update_faction_units() -> None:
    path = "src/data/factions.ts"
    source = read(path)
    for unit_id, variant in UNIT_VARIANTS.items():
        pattern = re.compile(
            rf"(id:\s*['\"]{re.escape(unit_id)}['\"][\s\S]*?visual:\s*\{{)([\s\S]*?)(\n\s*\}})"
        )
        match = pattern.search(source)
        if match is None or "variant:" in match.group(2):
            continue
        indentation_match = re.search(r"\n(\s*)\S", match.group(2))
        indentation = indentation_match.group(1) if indentation_match else "      "
        replacement = (
            match.group(1)
            + f"\n{indentation}variant: '{variant}',"
            + match.group(2)
            + match.group(3)
        )
        source = source[:match.start()] + replacement + source[match.end():]
    write(path, source)


FALLBACK_HELPER = """const CARNAGE_FALLBACK_VARIANT: Record<string, import('../gfx/carnageVisualVariants').CarnageVisualVariant> = {
  man_at_arms: 'corrupted-infantry',
  longbowman: 'corrupted-longbow',
  pikeman: 'corrupted-pike',
  knight: 'corrupted-knight',
  battle_monk: 'corrupted-monk',
  field_surgeon: 'corrupted-surgeon'
}

function fallbackCarnageVariant(base: UnitDef): import('../gfx/carnageVisualVariants').CarnageVisualVariant {
  const direct = CARNAGE_FALLBACK_VARIANT[base.id]
  if (direct) return direct
  const name = base.name.toLowerCase()
  if (name.includes('longbow')) return 'corrupted-longbow'
  if (name.includes('pike')) return 'corrupted-pike'
  if (name.includes('knight')) return 'corrupted-knight'
  if (name.includes('monk')) return 'corrupted-monk'
  if (name.includes('surgeon')) return 'corrupted-surgeon'
  return 'corrupted-infantry'
}

"""


def update_morphs() -> None:
    path = "src/data/morphs.ts"
    source = read(path)
    marker = "function carnageVisualFor("
    if "CARNAGE_FALLBACK_VARIANT" not in source:
        index = source.find(marker)
        if index < 0:
            raise RuntimeError("carnageVisualFor not found")
        source = source[:index] + FALLBACK_HELPER + source[index:]

    source = re.sub(
        r"(function\s+carnageVisualFor\s*\(base:\s*UnitDef\)[^{]*\{)(?!\s*\n\s*const variant)",
        r"\1\n  const variant = fallbackCarnageVariant(base)",
        source,
        count=1,
    )
    match = re.search(r"function\s+carnageVisualFor\s*\(base:\s*UnitDef\)[^{]*\{", source)
    if match is None:
        raise RuntimeError("carnageVisualFor missing after helper insertion")
    depth = 0
    end = None
    for index in range(match.end() - 1, len(source)):
        if source[index] == "{":
            depth += 1
        elif source[index] == "}":
            depth -= 1
            if depth == 0:
                end = index + 1
                break
    if end is None:
        raise RuntimeError("Could not find carnageVisualFor end")
    block = source[match.start():end]
    block = re.sub(r"return\s*\{(?!\s*variant)", "return { variant,", block)
    source = source[:match.start()] + block + source[end:]
    write(path, source)


def update_render_harness() -> None:
    path = "scripts/render-carnage.mjs"
    source = read(path)
    if "async function captureCloseups" not in source:
        marker = "async function captureTechTree()"
        index = source.find(marker)
        if index < 0:
            raise RuntimeError("captureTechTree marker not found")
        closeups = """async function captureCloseups() {
  const seen = new Set()
  for (const age of [1, 2, 3, 4]) {
    await boot(12_000 + age)
    const roster = await configureCarnage(age, { ascended: age === 4 })
    for (const def of roster) {
      const slug = def.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
      if (seen.has(slug)) continue
      seen.add(slug)

      await boot(13_000 + age * 100 + seen.size)
      const liveRoster = await configureCarnage(age, { ascended: age === 4 })
      const live = liveRoster.find(candidate => candidate.name === def.name || candidate.id === def.id)
      if (!live) continue
      await spawnRoster([live])
      await stageRoster([live], age)
      await page.waitForTimeout(300)
      await page.screenshot({
        path: path.join(OUT_DIR, `unit-${slug}.png`),
        fullPage: true
      })
    }
  }
}

"""
        source = source[:index] + closeups + source[index:]
    if "await captureCloseups()" not in source:
        source = source.replace(
            "  for (const age of [1, 2, 3, 4]) await captureRoster(age)\n  await captureTechTree()",
            "  for (const age of [1, 2, 3, 4]) await captureRoster(age)\n  await captureCloseups()\n  await captureTechTree()",
        )
    write(path, source)


def add_validation() -> None:
    write(
        "scripts/validate-carnage-visuals.mjs",
        """import { readFile } from 'node:fs/promises'

const [types, factions, morphs, art] = await Promise.all([
  readFile('src/data/types.ts', 'utf8'),
  readFile('src/data/factions.ts', 'utf8'),
  readFile('src/data/morphs.ts', 'utf8'),
  readFile('src/gfx/carnageVisualVariants.ts', 'utf8')
])

const authored = [
  'husk', 'flenser', 'butcher', 'flensing-host', 'ripjaw', 'ripjaw-alpha',
  'skinrider', 'carrion-choir', 'shrike', 'headsman', 'monstrum', 'great-maw',
  'carrion-widow', 'widow-queen', 'charnel-engine', 'flesh-wall', 'incarnation'
]
const corrupted = [
  'corrupted-infantry', 'corrupted-longbow', 'corrupted-pike',
  'corrupted-knight', 'corrupted-monk', 'corrupted-surgeon'
]

if (!types.includes('variant?: CarnageVisualVariant')) {
  throw new Error('UnitVisual is missing the Carnage variant contract')
}
for (const variant of authored) {
  if (!factions.includes(`variant: '${variant}'`)) {
    throw new Error(`Authored Carnage unit is missing visual variant ${variant}`)
  }
  if (!art.includes(`case '${variant}'`)) {
    throw new Error(`Procedural art is missing ${variant}`)
  }
}
for (const variant of corrupted) {
  if (!morphs.includes(`'${variant}'`) || !art.includes(`case '${variant}'`)) {
    throw new Error(`Corrupted-human design is missing ${variant}`)
  }
}
console.log(`Carnage visual validation passed (${authored.length + corrupted.length} distinct silhouettes)`)
""",
    )

    package_path = "package.json"
    package_source = read(package_path)
    package_source = package_source.replace(
        '"check:carnage": "node scripts/check-carnage.mjs"',
        '"check:carnage": "node scripts/check-carnage.mjs && node scripts/validate-carnage-visuals.mjs"',
    )
    write(package_path, package_source)


def main() -> None:
    write("src/gfx/carnageVisualVariants.ts", visual_module())
    update_types()
    update_dispatcher()
    update_faction_units()
    update_morphs()
    update_render_harness()
    add_validation()


if __name__ == "__main__":
    main()
